croneter/PlexKodiConnect

resources/lib/itemtypes.py
resources/lib/utils.py

This makes PlexKodiConnect compatible to Krypton, currently at least.

made it compatible to Krypton

---

resources/lib/itemtypes.py
resources/lib/kodidb_functions.py

This doesn't handle artwork since Plex doesn't provide it, it also doesn't handle removal of sets since I believe that would require another query to see if the sets are referenced by any movies.

Quick hack to get sets working

---

resources/language/Czech/strings.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/croneter/plexkodiconnect/195)

Add Czech language

---

resources/lib/playutils.py

changed h265 to h264 as this should be the intended codec.

Hi10p should only trigger on h264

---

resources/lib/library_sync/full_sync.py

This reverts commit b86a6549acc0fb1547723f3bd15c0dc415c221fc.

Fix widgets not displaying correct playstate after PKC startup

---

default.py
resources/language/resource.language.en_gb/strings.po
resources/lib/initialsetup.py
resources/lib/utils.py
resources/lib/windows/direct_path_sources.py
resources/settings.xml
resources/skins/Main/1080i/script-plex-options_dialog.xml

Also see the wiki: https://github.com/croneter/PlexKodiConnect/wiki/Set-up-Direct-Paths
- Fixes #589 
- Fixes #72 
- Fixes #628

Better, safer way to enter network credentials for Direct Paths

---

resources/lib/kodi_db/__init__.py
resources/lib/library_sync/full_sync.py
resources/lib/playlist_func.py

Hopefully fix slow playback startup just after Kodi startup

---

resources/lib/plex_api.py

Fix to correctly escape paths

---

resources/lib/library_sync/websocket.py

Fix keyError 'sessionKey' for weird PMS messages

---

resources/lib/playlists/pms.py

Fix playlist sync: sequence item 0: expected string or unicode

---

resources/lib/library_sync/full_sync.py
resources/lib/plex_db/common.py

Fix PKC not deleting all the items it should

---

resources/lib/sync.py

Fix artwork caching AttributeError: 'ImageCachingThread' object has no attribute 'cancel'

---

resources/lib/initialsetup.py

Improve pop-up "Searching for PMS"

---

resources/lib/library_sync/__init__.py
resources/lib/library_sync/common.py
resources/lib/library_sync/full_sync.py
resources/lib/library_sync/websocket.py
resources/lib/sync.py

Fix PKC crashing on Xbox

---

resources/lib/app/connection.py
resources/lib/downloadutils.py
resources/lib/initialsetup.py
resources/lib/plex_functions.py
resources/lib/service_entry.py

Addresses issue #664: PKC might be able to connect to the PMS otherwise, BUT then Kodi won't display Posters and videos can't be played

Never ignore SSL certificate errors for Kodi >= 18 - just like Kodi

---

resources/lib/itemtypes/music.py
resources/lib/kodi_db/music.py
resources/lib/library_sync/full_sync.py

Fix music items getting deleted on startup

---

resources/lib/entrypoint.py

Fix extras not playing

---

resources/lib/websocket.py
resources/lib/websocket_client.py

Redirects seen e.g. with Cloudflare, issue #663

Allow websocket redirects. Never allow insecure HTTPs connections for Kodi Leia

---

resources/lib/itemtypes/common.py
resources/lib/itemtypes/movies.py
resources/lib/itemtypes/tvshows.py
resources/lib/kodi_db/video.py
resources/lib/kodimonitor.py
resources/lib/library_sync/full_sync.py
resources/lib/library_sync/sections.py
resources/lib/library_sync/websocket.py
resources/lib/plex_db/common.py
resources/lib/plex_db/tvshows.py

Greatly speed up sync for episodes, especially for large libraries

---

resources/lib/library_sync/full_sync.py

Improve sync dialog

---

resources/lib/app/account.py
resources/lib/app/application.py
resources/lib/app/connection.py
resources/lib/app/libsync.py
resources/lib/artwork.py
resources/lib/backgroundthread.py
resources/lib/kodimonitor.py
resources/lib/library_sync/common.py
resources/lib/library_sync/fanart.py
resources/lib/library_sync/full_sync.py
resources/lib/library_sync/sections.py
resources/lib/library_sync/websocket.py
resources/lib/playback.py
resources/lib/playlists/__init__.py
resources/lib/playqueue.py
resources/lib/plex_api.py
resources/lib/plex_companion.py
resources/lib/plexbmchelper/listener.py
resources/lib/service_entry.py
resources/lib/sync.py
resources/lib/utils.py
resources/lib/websocket_client.py

Fix "Unauthorized for PMS" e.g. on switching Plex users

---

resources/lib/playlists/kodi_pl.py

Fix rare case where thousands of identical playlists could be generated

---

resources/lib/library_sync/websocket.py

Fix background sync crashing in rare cases

---

addon.xml

- Bumps both dependency add-ons
- Fix UnicodeDecodeError: 'ascii' codec can't decode

Fix playback not starting at all

---

resources/lib/variables.py

dsplayer uses different DB versions for both video and music DB.
- Fixes #742

Fix PKC not starting due to a higher version Kodi database

---

resources/lib/playqueue.py

Fix PKC trying to initialize playqueues over and over again

---

resources/lib/variables.py

Fix PKC not synching new items if an older Kodi db is present

---

README.md
addon.xml
changelog.txt
resources/lib/migration.py

Beta version bump 2.7.5

---

resources/lib/library_sync/time.py

Fix float() argument must be a string or a number

---

resources/lib/kodi_db/__init__.py
resources/lib/playlist_func.py

Fix playback sometimes not being reported for direct paths

---

resources/lib/entrypoint.py
resources/lib/library_sync/sections.py

Fix nodes for skin use

---

resources/lib/entrypoint.py
resources/lib/widgets.py

Fix widgets not working in some cases, e.g. Nvidia Shield

---

resources/lib/widgets.py

Fix UnicodeDecodeError for libraries with non-ASCII paths

---

resources/lib/entrypoint.py

Fix TypeError on Kodi start

---

resources/lib/initialsetup.py

Fix Kodi Masterlock for nfs paths (requires restart)

---

resources/lib/music.py
resources/lib/variables.py

Fix duplicate music entries for direct paths (forces a Kodi database reset!)

---

default.py
resources/lib/artwork.py
resources/lib/defused_etree.py
resources/lib/library_sync/sections.py
resources/lib/path_ops.py
resources/lib/playback_starter.py
resources/lib/playlist_func.py
resources/lib/playlists/pms.py
resources/lib/plex_api.py
resources/lib/plex_companion.py
resources/lib/plex_functions.py
resources/lib/plexbmchelper/listener.py
resources/lib/utils.py
resources/lib/widgets.py

xml.etree.ElementTree sometimes returns str, sometimes unicode. Make sure we're always working with unicode to fix obscure bugs

Fixes to unicode

---

resources/lib/context_entry.py
resources/lib/plex_companion.py

Fix UnicodeEncodeError on playback startup for direct paths

---

resources/lib/kodimonitor.py

Attempt to fix rare Kodi crash on PKC exit

---

resources/lib/playutils.py

Fix 4k H265 not being transcoded

---

default.py
resources/language/resource.language.en_gb/strings.po
resources/lib/library_sync/nodes.py
resources/lib/library_sync/sections.py
resources/lib/service_entry.py
resources/settings.xml

Fix some appearance tweak settings

---

resources/lib/service_entry.py

Reload skin on resetting PKC video nodes

---

resources/lib/itemtypes/movies.py
resources/lib/itemtypes/music.py
resources/lib/itemtypes/tvshows.py
resources/lib/library_sync/full_sync.py
resources/lib/library_sync/sections.py
resources/lib/library_sync/websocket.py
resources/lib/plex_db/common.py
resources/lib/plex_db/movies.py
resources/lib/plex_db/music.py
resources/lib/plex_db/sections.py
resources/lib/plex_db/tvshows.py

This reverts commit edb9d6e2b0c6903f659654219632418d2565cb88, reversing
changes made to a603bd33ae49f94a0e8e4436c6230ed3f1b67d2c.

Revert "Merge pull request #841 from croneter/section-uuid"

---

default.py

Hopefully fix Kodi crashing on playback startup

---

addon.xml
resources/lib/playback.py

Hopefully fix Kodi crashing on playback startup for good

---

addon.xml
default.py
resources/lib/playback.py
resources/lib/playback_starter.py
resources/lib/transfer.py

 Another attempt to keep Kodi from crashing on playback startup

---

resources/lib/app/playstate.py
resources/lib/context_entry.py
resources/lib/json_rpc.py
resources/lib/playback.py
resources/lib/playlist_func.py
resources/lib/plex_api.py
resources/lib/utils.py

Fixes to playback startup

---

resources/lib/transfer.py

Fix playback startup and RuntimeError: Unknown exception thrown from the call "XBMCAddon::xbmcplugin::setResolvedUrl"

---

resources/lib/transfer.py
resources/lib/utils.py

Fix ValueError if casting to int/float

---

resources/lib/kodi_db/video.py

- Fixes #885 
- Fixes #887 
- Regression from #871

Fix In Progress widgets being broken and tv shows showing up as completely watched

---

resources/lib/transfer.py

Fix for Kodi 17 Krypton TypeError on playback start: 'offscreen' is an invalid keyword argument for this function

---

resources/lib/kodimonitor.py
resources/lib/plex_functions.py

- PKC now supports [Up Next](https://github.com/im85288/service.upnext/wiki) also for PKC add-on paths
- Fixes #923

Support for the Up Next Kodi add-on

---

resources/lib/playback.py

Fix AttributeError: 'NoneType' object has no attribute 'attrib' on playback startup

---

resources/lib/plex_companion.py

Fix Plex Companion casting from iOS and Android

---

resources/lib/kodimonitor.py
resources/lib/playlist_func.py
resources/lib/playqueue.py

Fix playback report not working after having played a non-Plex video file

---

resources/lib/app/libsync.py
resources/lib/itemtypes/common.py
resources/lib/itemtypes/movies.py
resources/lib/itemtypes/music.py
resources/lib/itemtypes/tvshows.py
resources/lib/library_sync/full_sync.py
resources/lib/library_sync/sections.py

Fix PKC background sync synching items to Kodi even though entire section should not be synched

---

resources/lib/initialsetup.py

Only enforce advancedsettings.xml 'cleanonupdate' to be false for PKC add-on paths

---

resources/lib/migration.py

- Caused by https://github.com/croneter/PlexKodiConnect/pull/977

Force-scan every single item in the library - seems like we could lose some recently added items otherwise when updating PKC

---

resources/lib/utils.py

Fix rare AttributeError on PKC startup when modifying advancedsettings.xml

---

resources/lib/app/playstate.py
resources/lib/kodimonitor.py

Fix PKC increasing the Plex watch count by 2 instead of 1

---

resources/lib/kodimonitor.py
resources/lib/playback.py

Fix external subtitles not being available

---

resources/lib/kodimonitor.py
resources/lib/playback.py
resources/lib/playback_starter.py
resources/lib/playlist_func.py
resources/lib/plex_api/base.py
resources/lib/plex_companion.py
resources/lib/timing.py

Fix resume not working in some cases

---

resources/lib/playback.py

Fix PKC resuming instead of playing from the beginning

---

resources/lib/kodimonitor.py
resources/lib/playback.py
resources/lib/service_entry.py

Get rid of ContextMonitor and the dedicated Python thread - with new resume mechanics, this is not needed anymore

---

resources/lib/kodimonitor.py

Optimize clean-up of file table in the Kodi video database after stopping playback

---

resources/lib/app/playstate.py
resources/lib/kodimonitor.py

Fix resume when using an external player

---

resources/lib/music.py

Fix a couple of issues with music when using direct paths: correctly escape music paths for Kodi regex matching

---

resources/lib/backgroundthread.py
resources/lib/db.py
resources/lib/library_sync/common.py
resources/lib/library_sync/fill_metadata_queue.py
resources/lib/library_sync/full_sync.py
resources/lib/library_sync/get_metadata.py
resources/lib/library_sync/process_metadata.py
resources/lib/library_sync/sections.py
resources/lib/plex_db/common.py
resources/lib/variables.py

Supersedes https://github.com/croneter/PlexKodiConnect/pull/1067

Rewire library sync to speed it up and fix sync getting stuck in rare cases

---

resources/lib/playlists/__init__.py

Fix OperationalError when starting with a fresh PKC installation

---

resources/lib/variables.py

Fix PKC not starting up on iOS

---

resources/lib/app/application.py
resources/lib/backgroundthread.py

- Fixes a regression introduced by https://github.com/croneter/PlexKodiConnect/pull/1073

Fix PKC becoming unresponsive e.g. when switching the PMS

---

default.py
resources/lib/entrypoint.py

Other Kodi add-ons can now search for Plex items using plugin://plugin.video.plexkodiconnect?mode=search&query=<your search string here>

---

resources/lib/backgroundthread.py
resources/lib/library_sync/fill_metadata_queue.py
resources/lib/library_sync/full_sync.py
resources/lib/library_sync/process_metadata.py

Fix rare but annoying bug where PKC becomes unresponsive during sync

---

resources/lib/backgroundthread.py
resources/lib/library_sync/fill_metadata_queue.py
resources/lib/library_sync/full_sync.py

Fix yet another rare but annoying bug where PKC becomes unresponsive during sync

---

resources/lib/context_entry.py
resources/lib/itemtypes/movies.py
resources/lib/itemtypes/music.py
resources/lib/itemtypes/tvshows.py
resources/lib/kodimonitor.py
resources/lib/migration.py
resources/lib/playback.py
resources/lib/playlists/kodi_pl.py
resources/lib/plex_api/file.py
resources/lib/widgets.py

Refactor direct and add-on paths. Enables use of Plex music playlists synched to Kodi

---

resources/lib/plex_api/file.py

Fix TypeError: 'NoneType' object has no attribute '__getitem__', e.g. when displaying albums

---

resources/lib/utils.py

Fix PKC crashing on devices running Microsoft UWP, e.g. XBox

---

resources/lib/kodimonitor.py

Fix PKC incorrectly marking a video as unwatched if an external player has been used

---

resources/lib/app/__init__.py
resources/lib/app/application.py
resources/lib/app/libsync.py
resources/lib/backgroundthread.py
resources/lib/entrypoint.py
resources/lib/service_entry.py
resources/lib/utils.py
resources/lib/websocket_client.py
resources/lib/windows/kodigui.py

- Finally fixes #191
- Fixes #1165

Fix websocket threads; enable PKC background sync for all Plex Home users!

---

resources/lib/app/application.py
resources/lib/backgroundthread.py
resources/lib/migration.py
resources/lib/service_entry.py

Fix PKC shutdown on Kodi profile switch

---

resources/lib/variables.py

This reverts commit 2e5249ca4fbf22a831c9b3a84d1a969d6c5751db.
Fixes #1178

Revert "Don't allow spaces in devicename"

---

resources/lib/sync.py

Fix sync dialog showing in certain cases even though user opted out

---

resources/lib/sync.py

Fix regression: sync dialog not showing up when it should

---

resources/lib/library_sync/sections.py

Fix UnboundLocalError when certain Plex sections are deleted or being un-synched

---

resources/lib/library_sync/fill_metadata_queue.py

Fix ValueError: invalid literal for int() with base 10 during show sync

---

resources/lib/plex_api/media.py

Fix playback failing due to caching of subtitles with non-ascii chars

---

resources/lib/itemtypes/movies.py

Kodi does not support multiple sets/collections per movie

Hopefully fix freeze during sync: Don't assign multiple sets/collections for a specific movie

---

resources/lib/plex_companion.py

Fix rare playback progress report failing and KeyError: u'containerKey'

---

resources/lib/playlists/__init__.py

Fix rare KeyError: None when trying to sync playlists

---

resources/lib/plex_api/artwork.py
resources/lib/plex_api/fanart_lookup.py

Greatly improve matching logic for The Movie Database if Plex does not provide an appropriate id

---

resources/lib/widgets.py

Fix rare KeyError when using PKC widgets

---

changelog.txt
resources/language/resource.language.cs_CZ/strings.po
resources/language/resource.language.da_DK/strings.po
resources/language/resource.language.de_DE/strings.po
resources/language/resource.language.es_AR/strings.po
resources/language/resource.language.es_ES/strings.po
resources/language/resource.language.es_MX/strings.po
resources/language/resource.language.fr_CA/strings.po
resources/language/resource.language.fr_FR/strings.po
resources/language/resource.language.hu_HU/strings.po
resources/language/resource.language.it_IT/strings.po
resources/language/resource.language.lt_LT/strings.po
resources/language/resource.language.lv_LV/strings.po
resources/language/resource.language.nl_NL/strings.po
resources/language/resource.language.no_NO/strings.po
resources/language/resource.language.pt_BR/strings.po
resources/language/resource.language.pt_PT/strings.po
resources/language/resource.language.ru_RU/strings.po
resources/language/resource.language.sv_SE/strings.po
resources/language/resource.language.uk_UA/strings.po
resources/language/resource.language.zh_CN/strings.po
resources/language/resource.language.zh_TW/strings.po
resources/lib/widgets.py

- Update changelog
- Fix rare KeyError when using PKC widgets
- Update translations

Merge from Kodi Leia

---

resources/lib/kodi_db/__init__.py

Fix AttributeError: module has no attribute try_decode

---

resources/lib/app/account.py
resources/lib/initialsetup.py
resources/lib/plex_functions.py
resources/lib/plex_tv.py
resources/lib/service_entry.py
resources/lib/windows/direct_path_sources.py

- Hopefully finally fixes #1099

Fix PKC suddenly using main Plex user's credentials, e.g. when the PMS address changed

---

resources/lib/itemtypes/movies.py

- Fixes #1266
- Partially fixes #689

Fix missing Kodi tags for movie collections/sets

---

resources/lib/service_entry.py

Fix Local variable 'user' referenced before assignement

---

resources/lib/plex_api/media.py
resources/lib/widgets.py

Fix pictures from Plex picture libraries not working/displaying

---

resources/language/resource.language.en_gb/strings.po
resources/lib/playback_decision.py
resources/settings.xml

Fix PKC not auto-picking audio/subtitle stream when transcoding

---

resources/lib/backgroundthread.py
resources/lib/library_sync/process_metadata.py

Hopefully fix rare case when sync would get stuck indefinitely

---

resources/lib/library_sync/sections.py
resources/lib/variables.py

Fix KeyError: u'game' if Plex Arcade has been activated

---

resources/lib/context_entry.py
resources/lib/initialsetup.py
resources/lib/utils.py

Fix TypeError: function missing required argument 'message'

---

resources/lib/itemtypes/tvshows.py
resources/lib/kodi_db/video.py
resources/lib/plex_api/base.py

Sync name and user rating of a TV show season to Kodi

---

resources/lib/service_entry.py

Fix UnboundLocalError: local variable 'user' referenced before assignment

---

resources/lib/websocket_client.py

Stumbled upon weired errors here: https://github.com/croneter/PlexKodiConnect/issues/1350

Improve logging for websocket JSON loads

---

resources/language/resource.language.en_gb/strings.po
resources/lib/websocket_client.py
resources/settings.xml

Add information to PKC settings for background sync and Alexa whether a connection has been successfully made

---

resources/lib/playback.py

Fix resume not working if Kodi player start-up is slow

---

resources/lib/itemtypes/movies.py
resources/lib/path_ops.py
resources/lib/plex_api/base.py
resources/lib/variables.py

Direct paths: fix filename showing instead of full video metadata during playback

---

resources/lib/pathvalidate/__init__.py
resources/lib/pathvalidate/__version__.py
resources/lib/pathvalidate/_base.py
resources/lib/pathvalidate/_common.py
resources/lib/pathvalidate/_const.py
resources/lib/pathvalidate/_filename.py
resources/lib/pathvalidate/_filepath.py
resources/lib/pathvalidate/_ltsv.py
resources/lib/pathvalidate/_symbol.py
resources/lib/pathvalidate/argparse.py
resources/lib/pathvalidate/click.py
resources/lib/pathvalidate/error.py
resources/lib/utils.py

Fix UnicodeEncodeError if Plex playlist name contains illegal chars

---

resources/lib/plexbmchelper/listener.py

Fix PKC not showing up as a casting target in some cases

---

resources/lib/variables.py

- Found while fiddling with issue #1447

Make sure that the correct file system encoding is used for playlists

---

resources/lib/itemtypes/movies.py
resources/lib/kodi_db/video.py
resources/lib/variables.py

Direct paths: corrections to more closely mirror Kodi's way of saving movie and tv show files to the db

---

resources/language/resource.language.en_gb/strings.po
resources/lib/app/libsync.py
resources/lib/plex_api/media.py
resources/settings.xml

Add PKC setting to disable verification whether we can access a media file

---

resources/lib/companion.py

Fix Alexa and RuntimeError: dictionary keys changed during iteration

---

resources/lib/library_sync/sections.py
resources/lib/path_ops.py

- Hopefully fixes #1470
- Hopefully fixes #1448

Fix AttributeError: module 'shutil' has no attribute 'copy_tree'

---

resources/lib/playlist_func.py

Fix a rare AttributeError when using playlists

---

addon.xml
resources/lib/json_rpc.py
resources/lib/kodi_constants.py
resources/lib/utils.py
resources/lib/widgets.py

Fix PKC widgets not working at all in some cases

---

resources/lib/websocket/_app.py

Attempt to fix websocket threading issues and AttributeError: 'NoneType' object has no attribute 'is_ssl' or 'settimeout'

---

resources/lib/websocket_client.py

Fix websockets and AttributeError: 'NoneType' object has no attribute

---

resources/language/resource.language.en_gb/strings.po
resources/lib/plex_api/media.py
resources/settings.xml

Fix auto-picking of video stream if several video versions are available

---

resources/lib/plex_api/base.py
resources/lib/utils.py

- Original pull request: https://github.com/croneter/PlexKodiConnect/pull/1528

Support for the Plex HAMA agent to let Kodi identify animes (using Kodi's uniqueID 'anidb')

---

resources/lib/utils.py

- Original pull request: https://github.com/croneter/PlexKodiConnect/pull/1528

Support forced HAMA IDs when using tvdb uniqueID

---

resources/lib/timing.py

Fix RecursionError: maximum recursion depth exceeded

---

resources/lib/library_sync/sections.py

Fix Regression: AttributeError

---

addon.xml

See https://github.com/croneter/PlexKodiConnect/pull/1562

Remove dependency on script.module.defusedxml - that module is now included in PKC

---

resources/lib/plex_api/media.py

- Fixes #1531 
- All credits go to @pannal and the PR https://github.com/plexinc/plex-for-kodi/pull/358

Fix PMS setting `List of IP addresses and networks that are allowed without auth` causing Kodi to take forever to start playback

---

resources/lib/playback_decision.py

- Fixes #1191 
- Partially fixes #1582

Fix PlexKodiConnect changing or removing subtitles for every video on the PMS

---

resources/lib/playback_decision.py

This reverts commit 3ef55f55267a220c110a3e69d417fe879e2da29d.
Had no effect

Revert "Fix PlexKodiConnect changing subtitles for all videos on the PMS"

---

resources/lib/playback_decision.py

- Fixes #1191, partially fixes #1582

Fix PlexKodiConnect setting the Plex subtitle to None

---

resources/lib/kodimonitor.py
resources/lib/playlist_func.py
resources/lib/subtitles.py

Use Plex settings for audio and subtitle stream selection. This is a best guess regarding subtitles as Plex and Kodi are not sharing much info

---

resources/lib/playback_decision.py

This reverts commit 4de0920bf54a5ecd64550d2e2cf1f082cc7f32ed.

Revert "Fix PlexKodiConnect changing subtitles for all videos on the PMS

---

resources/lib/kodi_db/video.py
resources/lib/kodimonitor.py

Implement "Reset resume position" from the Kodi context menu

---

resources/lib/path_ops.py

Fix RecursionError if a video lies in a root directory

---

resources/lib/db.py
resources/lib/exceptions.py
resources/lib/kodimonitor.py
resources/lib/playback.py
resources/lib/playlist_func.py
resources/lib/playlists/__init__.py
resources/lib/playlists/common.py
resources/lib/playlists/db.py
resources/lib/playlists/kodi_pl.py
resources/lib/playlists/plex_pl.py
resources/lib/playlists/pms.py
resources/lib/playqueue.py
resources/lib/plex_companion.py
resources/lib/subtitles.py

Large refactoring of playlist and playqueue code

---

resources/lib/playback_decision.py
resources/lib/plex_functions.py

Transcoding: Fix Plex burning-in subtitles when it should not

---

resources/lib/playback_decision.py
resources/lib/plex_api/base.py

Refactor usage of a media part's id

---

resources/lib/json_rpc.py
resources/lib/kodimonitor.py
resources/lib/playlist_func.py
resources/lib/plex_functions.py
resources/lib/variables.py

Tell the PMS if a video's audio stream or potentially subtitle stream has changed. For subtitles, this functionality is broken due to a Kodi bug

---

resources/lib/downloadutils.py
resources/lib/plex_api/artwork.py
resources/lib/plex_api/media.py

 Fix logging if fanart.tv lookup fails: be less verbose

---

resources/lib/utils.py

Android: Fix broken Python multiprocessing module (a Kodi 19.2 bug)

---

resources/language/resource.language.cs_CZ/strings.po
resources/language/resource.language.da_DK/strings.po
resources/language/resource.language.de_DE/strings.po
resources/language/resource.language.el_GR/strings.po
resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.es_AR/strings.po
resources/language/resource.language.es_ES/strings.po
resources/language/resource.language.es_MX/strings.po
resources/language/resource.language.fr_CA/strings.po
resources/language/resource.language.fr_FR/strings.po
resources/language/resource.language.hu_HU/strings.po
resources/language/resource.language.it_IT/strings.po
resources/language/resource.language.ko_KR/strings.po
resources/language/resource.language.lt_LT/strings.po
resources/language/resource.language.lv_LV/strings.po
resources/language/resource.language.nl_NL/strings.po
resources/language/resource.language.no_NO/strings.po
resources/language/resource.language.pl_PL/strings.po
resources/language/resource.language.pt_BR/strings.po
resources/language/resource.language.pt_PT/strings.po
resources/language/resource.language.ru_RU/strings.po
resources/language/resource.language.sv_SE/strings.po
resources/language/resource.language.uk_UA/strings.po
resources/language/resource.language.zh_CN/strings.po
resources/language/resource.language.zh_TW/strings.po
resources/lib/skip_plex_intro.py
resources/lib/windows/skip_intro.py
resources/settings.xml

Add auto skip intro sub-setting under the existing skip intro setting in the Playback section. This feature will automatically skip TV show intros instead of showing the **Skip intro** button.

Add auto skip intro functionality

---

default.py
resources/lib/clientinfo.py
resources/lib/service_entry.py
resources/lib/utils.py
resources/lib/variables.py
resources/lib/websocket_client.py
resources/lib/windows/kodigui.py

Fix generating new unique device ID for PKC not working

---

resources/lib/plex_companion/playstate.py
resources/lib/service_entry.py
resources/lib/skip_plex_intro.py

Fix skip intro not working

---

resources/lib/plex_companion/polling.py

Fix Kodi getting blocked and losing PMS access e.g. due to cloudflare

---

resources/lib/clientinfo.py

Fix PKC not being able to connect to plex.tv after installation

---

resources/lib/companion.py
resources/lib/plex_companion/__init__.py
resources/lib/plex_companion/common.py
resources/lib/plex_companion/playstate.py
resources/lib/plex_companion/plexgdm.py
resources/lib/plex_companion/polling.py
resources/lib/plex_companion/processing.py
resources/lib/plex_companion/webserver.py
resources/lib/service_entry.py
resources/lib/utils.py
resources/lib/variables.py
resources/lib/websocket_client.py

Re-add old Plex Companion mechanism as the new one sucks

---

resources/lib/kodimonitor.py
resources/lib/playlist_func.py

Fix playback report for widget not working if direct paths are used

---

resources/lib/plex_companion/playqueue.py

Fix detection of playqueue order. Thus fix PKC reporting back the playing of an old episode when using UpNext

---

resources/lib/plex_api/artwork.py

Fix additional artwork download crashing if there was no sensible reply

---

resources/lib/kodimonitor.py

- Fixes #923 
- Fixes https://github.com/im85288/service.upnext/issues/267
- Fixes https://github.com/im85288/service.upnext/issues/250

Fix Kodi add-on `Up Next` crashing by removing code that has become obsolete on the PKC-side

---

resources/lib/kodimonitor.py

Fix playback report not working and AttributeError: 'NoneType' object has no attribute 'startswith'

---

resources/lib/playlist_func.py

Fix PKC not picking the correct Plex subtitle

---

resources/lib/plex_companion/playstate.py

Fix IndexError and playback progress not being reported to the PMS

---

resources/lib/kodi_db/video.py

Android: Fix IntegrityError during sync, caused by a screwed up Python environment

---

resources/lib/kodi_db/video.py

- Hopefully fixes #1777 
- PR #1790 only worked sporadically

Another attempt at: Android: Fix IntegrityError during sync, caused by a screwed up Python environment

---

resources/lib/kodi_db/video.py

Attempt to fix Android 11 with Experience 9 crashing

---

resources/lib/kodimonitor.py
resources/lib/plex_companion/playstate.py

Fix PKC reporting Kodi TV/PVR playback as the last Plex item being played again

---

resources/lib/variables.py

Add initial, experimental support for latest Nexus nightly, video DB version bump 120
