croneter/PlexKodiConnect

resources/lib/itemtypes.py

I am registering my direct paths for regular browsing with no metadata updates.
In the current releases (1.1.2 to 1.1.4) I saw only basic file information with no media
metadata from Plex.
The missing information is full file URL and path id. These are stores in movies
in c22 and c23, and in episodes in c18 and c19.
I have added the missing updates. And tested in Isengard,

Support for metadata display in file browser

---

resources/lib/librarysync.py

if the user deselects "show library sync progress" positive sync messages shouldnt be shown at all.
when the PlexKodiConnect client resumes from s3 sleep this message was shown every time the client was put to sleep before a server induced (even partial) library update which happens at least once a day.
due to the message is force shown it can get quite annoying as the user has no option to silence the message.
this attaches the message to the user configurable option "show library sync progress".

sync: dont force show "full library sync finished"

---

README.md
resources/language/English/strings.xml
resources/language/German/strings.xml
resources/lib/initialsetup.py

Raspberry Pi is a proper name thus should be capitalised.
also use "device" instead of "computer" in german translation to bring it in line with the english phrasing.
as kodi can also be deployed on devices which are not necessarily categorized as "computers" in the proper sense (e.g. mobile devices), "device" should fit better here and is correctly utilized in the english translation.

fix 'raspberry pi' spelling and capitalisation

---

resources/lib/PlexAPI.py

This feature was requested in issue https://github.com/croneter/PlexKodiConnect/issues/164. 
It is quite simple to implement by passing the path of the RAW image file, through the
getTranscodeImagePath function in the PlexAPI class. The path is then exchanged for `https://<plexip>:32400/photo/:/transcode/1920x1080/<path>?url=http://127.0.0.1:32400/<key>&width=1920&height=1080&Plex-Token=<token>`. This requests Plex
to transcode the file before sending it to Kodi. The 127.0.0.1 address directs plex to itself instead and is basically the same as using the server url.
- This is always active for all RAW files, there is support for RAW files in Kodi but with issues (e.g. http://forum.kodi.tv/showthread.php?tid=167127, but my own .ARW files did not work either in Kodi). It might be better to …

Plex RAW photos/picture support

---

resources/lib/entrypoint.py

This covers part 2 of issue #190.
I plan on doing a separate PR for part 1, as that one is more complex and should allow you to decide independently if you want to merge the changes.
Should you prefer to receive proposals differently, feel free to let me know. 
At this point I would also like to mention that I think the second part of getOnDeck should be removed in my opinion as it does not really mimic Plex and the result would look different from PMS itself. Besides, if someone wanted to see the next Episode of all shows, there would already be the method 'nextUpEpisodes', which could be added as a separate video node. 
If you were to agree with this, please note that the Appearance Tweak settings 'Extend OnDeck to all Shows' would become obsolete as a pure "OnDeck" does not allow that. …

apply limit to OnDeck if OnDeckTVextended not set

---

default.py

The `entrypoint.py` subs `getNextUpEpisodes` and `getInProgressEpisodes` are expecting 'tagname' as first argument, not 'itemid'. With this fix the query works, e.g. with a manually generated video-node.
It does seem to have a logical issue though as it always filters for "inprogress" TV Shows, regardless of the PKC Parameter "Extend Plex TV Series 'On Deck' view to all shows". You may argue that this setting was meant for OnDeck only, but the second part of `getOnDeck` also contains that filter (line 794).
I will probably try to get a "Next Up Episodes" video-node to the PKC generated TV Show folder, but if I get to it I'll produce a separate PR for that.
Thanks again for your great on this awesome tool.

fix small bug to get nextup woking

---

resources/lib/plexbmchelper/listener.py

Causes issues with Plex web due to Access-Control-Allow-Headers missing header.
I was getting the following browser error:
XMLHttpRequest cannot load http://***:3005/player/timeline/poll?wait=0&commandID=0. Request header field X-Plex-Device-Screen-Resolution is not allowed by Access-Control-Allow-Headers in preflight response.

Fix Plex Web Issue

---

resources/lib/artwork.py

Because kodi doesn't do that until after restart.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/croneter/plexkodiconnect/393)

Restore cache directories after deleting. Fixes #392

---

resources/lib/itemtypes/common.py
resources/lib/itemtypes/music.py

Still delete artwork - left-over artwork, even if it's from Artwork Beef, is useless.
- Partially fixes #622

Fix 'NoneType' object has no attribute 'execute' when Plex artwork is not synced and an item is deleted

---

resources/lib/path_ops.py

os.path is not really working with smb and possibly other protocols. Thus use Kodi's xbmcvfs module. For that to work, remote (smb) sources need to be set:
* explicitly in `sources.xml`
* username and password in `passwords.xml`
Also see the [PKC wiki entry](https://github.com/croneter/PlexKodiConnect/wiki/Set-up-Direct-Paths)

Fix check whether a direct path is accessible

---

resources/lib/plex_db/common.py

* One should not create an index on a `PRIMARY KEY` column - useless and even slows things down
* Introduces lookups for `last_sync` and `kodi_id` columns in the plex.db
Theoretically, we should reset the plex database. Let's not do that.

Improve plex db lookups by creating better db indicees

---

resources/lib/kodimonitor.py
resources/lib/service_entry.py
resources/lib/websocket_client.py

Calls to `xbmc.getCondVisibility` when PKC should exit (`xbmc.abortRequested=True`?) will never return

Fix Kodi profile switch not working correctly and PKC not exiting cleanly

---

resources/lib/library_sync/sections.py

Fix sync not working due to non-ASCII Plex library names

---

resources/lib/context_entry.py

- Refresh is done already once the PMS notices PKC that item has been refreshed or deleted (via websockets)

Don't refresh container when user chose to delete or refresh an item from the context menu

---

resources/lib/plex_api/file.py

- Fixes #863
- urllib.unquote() is not needed anymore for Plex' `file` attribute
- urllib.unquote() seems to choke on `%` that are not to be unquoted(?)

Fix rare UnicodeDecodeError on library sync

---

resources/lib/music.py

- Fixes #886
- Regression from #871

Fix TypeError for Direct Paths: init() got an unexpected keyword argument ‘item’

---

resources/lib/itemtypes/tvshows.py

- Fixes #870 
- You will need to manually reset the Kodi database in the PKC settings under Advanced

Fix Trakt add-on not recognizing id of tv shows

---

resources/lib/migration.py
resources/lib/playlists/db.py
resources/lib/plex_db/common.py
resources/lib/plex_db/playlists.py

- Cause: unique index wasn't really unique. Python sqlite failed silently (thanks very much)
- To reproduce the original bug: simply copy-paste an existing playlist file on the Kodi side

 Fix PKC creating thousands of playlists if a single Kodi playlist wasn't unique

---

resources/lib/library_sync/sections.py

Fix 'Plex.nodes.<id>.path' not linking directly to entire library

---

resources/lib/library_sync/nodes.py

- Let's skinners always use the `ondeck` node, see #745

Rename video nodes for ondeck

---

resources/lib/migration.py
resources/lib/playlists/__init__.py
resources/lib/playlists/common.py
resources/lib/playlists/kodi_pl.py
resources/lib/utils.py

Use file size and last modification timestamp to check whether a Kodi playlist has changed instead of a md5 hash of the entire playlist (which is very slow)

Faster sync of playlists

---

resources/lib/service_entry.py

- Made necessary due to PR #977 where enabling a Plex section's sync to Kodi led to items not actually being synched

Force a full sync of all items after choosing a new PMS, changing a PMS' address and changing which Plex libraries to sync

---

resources/lib/plex_api/media.py
resources/lib/service_entry.py
resources/lib/utils.py

Issue was, that the entire URL got escaped after just being split into three parts along the `:`. You'l be left with e.g. an `:` and `@` when using `username:password@hostname:port` that should NOT be further escaped

Correctly escape URLs for Direct Paths

---

resources/lib/playback.py
resources/lib/plex_functions.py

- Introduced by 0d7a1b3a9f1828b550d508848c2b3e07801bbcf8
- Fixes #999

Fix Play Error in scenarios (older PMS version?) where posting playqueues using an uri `server://` is not possible and `library://` is necessary

---

resources/lib/playlists/db.py

- Also see https://github.com/croneter/PlexKodiConnect/pull/1021

Fix PKC throwing error if m3u playlist contains resume information

---

resources/lib/itemtypes/movies.py
resources/lib/itemtypes/music.py
resources/lib/itemtypes/tvshows.py
resources/lib/utils.py

Fix DirectPaths when a video's folder name is identical to a video's filename (you will need to manually reset the Kodi database)

---

resources/lib/downloadutils.py
resources/lib/playback.py
resources/lib/playback_decision.py
resources/lib/plex_functions.py

Rewire the set-up of audio and subtitle streams, esp. before starting a transcoding session. Fixes playback not starting at all

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.es_ES/strings.po
resources/lib/app/libsync.py
resources/lib/plex_api/media.py
resources/lib/utils.py
resources/settings.xml

**Added support for custom set of safe characters (configured via addon settings) when escaping paths using direct paths for http(s), dav(s) and (s)ftp URLs.**
Currently the following characters are defined as safe (i.e. not being escaped) when escaping direct paths: `%/:=&?~#+!$,;'@()*[]`
When I was trying to get rclone to serve my google drive content in a webdav server, I realised that (at least) parenthesis and brackets should be escaped, thus the need for specifying a custom set of safe characters. I have successfully made this setup work with `/+` as custom set of safe characters.
I have added an option to the addon settings to specify the list of characters not to be escaped, which by default will be the same as the currently hard-coded set.
This custom set will only be used if the …

Added support for custom set of safe characters when escaping paths

---

resources/lib/backgroundthread.py
resources/lib/plex_companion.py
resources/lib/plex_functions.py
resources/lib/windows/kodigui.py

Python 3.9 has removed the method `thread.isAlive` and `thread.is_alive` should be used. This should be compatble with previous versions, as `thread.is_alive` exists also on Python 2.

Change `thread.isAlive` to `thread.is_alive`

---

resources/lib/timing.py

- Discovered when connecting to the users library in #1295

Fix OSError: Invalid argument when Plex returns an invalid timestamp

---

resources/lib/library_sync/fill_metadata_queue.py
resources/lib/plex_api/base.py

Fix ValueError: invalid literal for int() for invalid dates sent by Plex

---

resources/lib/library_sync/fill_metadata_queue.py
resources/lib/plex_api/base.py

ValueError: invalid literal for int() for invalid dates sent by Plex

---

resources/lib/path_ops.py

Fix ImportError: cannot import name 'dir_util' from 'distutils' on PKC startup

---

addon.xml
resources/lib/utils.py
resources/lib/widgets.py

- Hopefully fixes #1488
- Hopefully fixes `script.skin.helper` and `script.skin.helper.backgrounds` exceptions like
```
2021-05-24 11:39:25.561 T:31113 WARNING <general>: Skin Helper Backgrounds --> Exception details: Type: ModuleNotFoundError Value: No module named 'Image' Traceback: Traceback (most recent call last):
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.backgrounds/resources/lib/wallimages.py", line 24, in <module>
from PIL import Image
ModuleNotFoundError: No module named 'PIL'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.backgrounds/resources/lib/wallimages.py", line 32, in <module> …
```

Get rid of Python arrow; hopefully fix many Python import errors (also occuring in other add-ons!)

---

resources/lib/websocket/_core.py

- As detailed here (unfortunately fix is unavailable for Python 2): https://github.com/websocket-client/websocket-client/issues/720

Websocket Fix AttributeError: 'NoneType' object has no attribute 'is_ssl'

---

resources/lib/plex_api/base.py

Direct Paths: Fix TypeError: "element indices must be integers" on playback startup

---

resources/lib/plex_companion/common.py
resources/lib/variables.py

- Fixes #1696
- Regression introduced in #1694 
- This reverts commit f2e2be6da7a21d7e89c0bad1d9922c1e2f4e2aaa.

Fix playback startup and AttributeError: 'bool' object has no attribute 'get'

---

resources/lib/artwork.py

Make sure that no proxy is used for artwork caching for calls to Kodi's webserver at `localhost`
